services:
  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt


volumes:
  db_data:
  wordpress_data:

networks:
  inception:

