services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    secrets:
      - db_password
      - db_root_password
      - db_admin_password

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html:ro
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_admin_password:
    file: ../secrets/db_admin_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vboxuser/data/mariadb #the vboxuser should be the user on VM

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vboxuser/data/wordpress

networks:
  inception:
    driver: bridge